# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Build documentation with Python 3.11
python:
  install:
    - requirements: docs/requirements.txt
  system_packages: true

# Build with a modern OS
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
